[project]
name = "map-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "geodesk>=1.1.0",
    "geojson>=3.2.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "scipy>=1.15.2",
]
